const PRIMARY = '#41ADDD';
const SECONDARY = '#FFFFFF';
const LIGHT_SECONDARY = '#CCCCCC';
const TERTIARY = '#000000';


export const COLORS = {
  FONT: SECONDARY,
  HOVER: LIGHT_SECONDARY,
  BACKGROUND: PRIMARY,
}
